# Versions were last checked on 2026 Jul 29.

# Up to 1.12.14
# Avoid "java.lang.OutOfMemoryError: Required array size too large" of 1.4+.
# Versions in the 1.3+ range seem to break the sbt-dependency-graph plugin and ivy-related things.
sbt.version = 1.12.14
